INSERT INTO category (CATEGORY_NAME ) VALUES ('American'); 
INSERT INTO category (CATEGORY_NAME ) VALUES ('Italian');
INSERT INTO category (CATEGORY_NAME ) VALUES ('Mexican'); 
INSERT INTO category (CATEGORY_NAME ) VALUES ('Fast Food'); 
INSERT INTO category (CATEGORY_NAME ) VALUES ('Indian');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Pound');
